title: Vac
description: VAC researches peer-to-peer, private, censorship resistant communication.
baseurl: ""
url: "http://localhost:4000/"
# url: "https://vac.dev"

exclude:
  - Gemfile
  - Gemfile.lock
  - gulpfile.babel.js
  - LICENSE.md
  - node_modules
  - package.json
  - package-lock.json
  - README.md
  - src
  - tailwind.config.js
  - netlify.toml
  - vendor

collections:
  authors:
    output: true

defaults:
  - scope:
      path: "assets/img"
    values:
      image: true
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
