title: Vac
description: VAC researches peer-to-peer, private, censorship resistant communication.

exclude:
  - Gemfile
  - Gemfile.lock
  - gulpfile.babel.js
  - LICENSE.md
  - node_modules
  - package.json
  - package-lock.json
  - README.md
  - src
  - tailwind.config.js
  - netlify.toml
  - vendor

defaults:
  - scope:
      path: "assets/img"
    values:
      image: true
