title: Vac
description: VAC researches peer-to-peer, private, censorship resistant communication.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://localhost:4000/" # the base hostname & protocol for your site, e.g. http://example.com

exclude:
  - Gemfile
  - Gemfile.lock
  - gulpfile.babel.js
  - LICENSE.md
  - node_modules
  - package.json
  - package-lock.json
  - README.md
  - src
  - tailwind.config.js
  - netlify.toml
  - vendor

defaults:
  - scope:
      path: "assets/img"
    values:
      image: true
